CREATE TABLE employees (
    emp_id INT PRIMARY KEY,
    emp_name VARCHAR(100) NOT NULL,
    emp_salary DECIMAL(10, 2) NOT NULL,
      emp_city VARCHAR(100) NOT NULL
);

INSERT INTO employees (emp_id, emp_name, emp_salary, emp_city) VALUES
(101, 'Amit Sharma', 85000.00, 'Mumbai'),
(102, 'Priya Patel', 95000.00, 'Mumbai'),
(103, 'Rahul Verma', 60000.00, 'Delhi'),
(104, 'Ananya Iyer', 110000.00, 'Bangalore'),
(105, 'Vikram Singh', 55000.00, 'Delhi'),
(106, 'Sneha Reddy', 105000.00, 'Bangalore'),
(107, 'Rohan Das', 72000.00, 'Kolkata')

-- AGGREGATE FUNCTION -> SUM(),MIN(),MAX(),AVG(),COUNT()


-- COUNT THE NUMBER OF EMPLOYEES IN EACH CITY

-- (I) 
SELECT EMP_CITY,COUNT(*) AS CNT FROM EMPLOYEES
GROUP BY EMP_CITY

-- (II)
SELECT EMP_CITY,COUNT(EMP_ID) AS CNT FROM EMPLOYEES
GROUP BY EMP_CITY


-- COUNT THRE NUMBER OF EMPLOYEE IN EACH CITY WHOSE SALARY SALARY IS GRETARE THAN EQUAL TO 90000


SELECT EMP_CITY,SUM(CASE WHEN EMP_SALARY>=90000 THEN 1 ELSE 0 END) AS CNT FROM EMPLOYEES
GROUP BY EMP_CITY



-- COUNT THRE NUMBER OF EMPLOYEE IN EACH CITY WHOSE SALARY SALARY IS GRETARE THAN EQUAL TO 90000
-- AND SORT ON THE BASIS OF CITY NAME IN DESCENDING ORDER


SELECT EMP_CITY,SUM(CASE WHEN EMP_SALARY>=90000 THEN 1 ELSE 0 END) AS CNT FROM EMPLOYEES
GROUP BY EMP_CITY
ORDER BY EMP_CITY DESC


-- COUNT THRE NUMBER OF EMPLOYEE IN EACH CITY WHOSE SALARY SALARY IS GRETARE THAN EQUAL TO 90000
-- AND SORT ON THE BASIS OF CNT IN DESC ORDER


SELECT EMP_CITY,SUM(CASE WHEN EMP_SALARY>=90000 THEN 1 ELSE 0 END) AS CNT FROM EMPLOYEES
GROUP BY EMP_CITY
ORDER BY CNT DESC,EMP_CITY DESC


-- FIND THE NAME OF THE CITY WHOSE EMPLOYEE COUNT AT LEAST 2

SELECT EMP_CITY AS CNT FROM EMPLOYEES
GROUP BY EMP_CITY
HAVING COUNT(EMP_ID)>=2



-- 
-- DISTINCT

SELECT DISTINCT EMP_CITY
FROM EMPLOYEES