SET SERVEROUTPUT ON;

CREATE TABLE EMPLOYEE (
    EMP_ID NUMBER PRIMARY KEY,
    EMP_NAME VARCHAR2(50),
    SALARY NUMBER
);

INSERT INTO EMPLOYEE VALUES (101, 'Rahul', 30000);
INSERT INTO EMPLOYEE VALUES (102, 'Aman', 40000);
INSERT INTO EMPLOYEE VALUES (103, 'Simran', 50000);
INSERT INTO EMPLOYEE VALUES (104, 'Karan', 0);
INSERT INTO EMPLOYEE VALUES (105, 'Priya', 60000);

COMMIT;

DECLARE
    CURSOR emp_cursor IS
        SELECT EMP_ID, SALARY FROM EMPLOYEE;

    V_EMP_ID EMPLOYEE.EMP_ID%TYPE;
    V_SALARY EMPLOYEE.SALARY%TYPE;

    SALARY_ZERO EXCEPTION;

BEGIN
    OPEN emp_cursor;

    FETCH emp_cursor INTO V_EMP_ID, V_SALARY;

    WHILE emp_cursor%FOUND
    LOOP
        IF V_SALARY = 0 THEN
            RAISE SALARY_ZERO;
        END IF;

        UPDATE EMPLOYEE
        SET SALARY = V_SALARY * 1.10
        WHERE EMP_ID = V_EMP_ID;

        FETCH emp_cursor INTO V_EMP_ID, V_SALARY;
    END LOOP;

    CLOSE emp_cursor;

EXCEPTION
    WHEN SALARY_ZERO THEN
        DBMS_OUTPUT.PUT_LINE('Salary is zero. Increment not possible.');
END;
/

SELECT * FROM EMPLOYEE;