DO $$
	DECLARE
	VAL INT:= 19;

	BEGIN

	IF VAL >= 0 AND VAL <= 10 THEN
	RAISE NOTICE 'VAL IS % AND RANGE BETWEEN 1 AND 10', VAL;

	ELSIF VAL > 10 AND VAL <= 20 THEN
	RAISE NOTICE 'VAL IS % AND RANGE BETWWEN 11 AND 20', VAL;

	ELSE
	RAISE NOTICE 'VAL IS % AND IS GREATER THAN 20', VAL;
	END IF;

	RAISE NOTICE 'YOU ARE INSIDE BEGIN END BLOCK';
	END;
$$